export const LEVEL_LABELS = { '12': 'Phase 1–2', '34': 'Phase 3–4' };
export const WORD_GOALS = { '12': 60, '34': 120 };
export const VOCAB_TARGET = { '12': 120, '34': 120 };

function v(id, es, en) {
  return { id, es, en };
}

export const vocabSetsByLevel = {
  '12': {
    'Family / Familia': [
      v('12-fam-madre', 'madre', 'mother'),
      v('12-fam-padre', 'padre', 'father'),
      v('12-fam-hermano', 'hermano', 'brother'),
      v('12-fam-hermana', 'hermana', 'sister'),
      v('12-fam-abuelo', 'abuelo', 'grandfather'),
      v('12-fam-abuela', 'abuela', 'grandmother'),
      v('12-fam-tio', 'tío', 'uncle'),
      v('12-fam-tia', 'tía', 'aunt'),
      v('12-fam-primo', 'primo', 'cousin (m)'),
      v('12-fam-prima', 'prima', 'cousin (f)'),
      v('12-fam-hijo', 'hijo', 'son'),
      v('12-fam-hija', 'hija', 'daughter'),
      v('12-fam-padres', 'padres', 'parents'),
      v('12-fam-familia', 'familia', 'family'),
      v('12-fam-bebe', 'bebé', 'baby'),
      v('12-fam-sobrino', 'sobrino', 'nephew'),
      v('12-fam-sobrina', 'sobrina', 'niece'),
      v('12-fam-nieto', 'nieto', 'grandson'),
      v('12-fam-nieta', 'nieta', 'granddaughter'),
      v('12-fam-mascota', 'mascota', 'pet'),
    ],
    'Food / Comida': [
      v('12-food-manzana', 'manzana', 'apple'),
      v('12-food-pan', 'pan', 'bread'),
      v('12-food-agua', 'agua', 'water'),
      v('12-food-leche', 'leche', 'milk'),
      v('12-food-pollo', 'pollo', 'chicken'),
      v('12-food-arroz', 'arroz', 'rice'),
      v('12-food-queso', 'queso', 'cheese'),
      v('12-food-fruta', 'fruta', 'fruit'),
      v('12-food-verdura', 'verdura', 'vegetable'),
      v('12-food-desayuno', 'desayuno', 'breakfast'),
      v('12-food-almuerzo', 'almuerzo', 'lunch'),
      v('12-food-cena', 'cena', 'dinner'),
      v('12-food-pescado', 'pescado', 'fish'),
      v('12-food-huevo', 'huevo', 'egg'),
      v('12-food-zumo', 'zumo', 'juice'),
      v('12-food-ensalada', 'ensalada', 'salad'),
      v('12-food-sopa', 'sopa', 'soup'),
      v('12-food-carne', 'carne', 'meat'),
      v('12-food-postre', 'postre', 'dessert'),
      v('12-food-hambre', 'hambre', 'hunger'),
    ],
    'School / Escuela': [
      v('12-sch-profesor', 'profesor', 'teacher (m)'),
      v('12-sch-profesora', 'profesora', 'teacher (f)'),
      v('12-sch-libro', 'libro', 'book'),
      v('12-sch-mochila', 'mochila', 'backpack'),
      v('12-sch-clase', 'clase', 'class'),
      v('12-sch-examen', 'examen', 'exam'),
      v('12-sch-pizarra', 'pizarra', 'whiteboard'),
      v('12-sch-tarea', 'tarea', 'homework'),
      v('12-sch-boligrafo', 'bolígrafo', 'pen'),
      v('12-sch-horario', 'horario', 'schedule'),
      v('12-sch-alumno', 'alumno', 'student (m)'),
      v('12-sch-alumna', 'alumna', 'student (f)'),
      v('12-sch-lapiz', 'lápiz', 'pencil'),
      v('12-sch-cuaderno', 'cuaderno', 'notebook'),
      v('12-sch-recreo', 'recreo', 'break / recess'),
      v('12-sch-asignatura', 'asignatura', 'subject'),
      v('12-sch-biblioteca', 'biblioteca', 'library'),
      v('12-sch-pupitre', 'pupitre', 'desk'),
      v('12-sch-regla', 'regla', 'ruler'),
      v('12-sch-goma', 'goma', 'eraser'),
    ],
    'Daily routine / Rutina': [
      v('12-rut-despertarse', 'despertarse', 'to wake up'),
      v('12-rut-ducharse', 'ducharse', 'to shower'),
      v('12-rut-desayunar', 'desayunar', 'to have breakfast'),
      v('12-rut-estudiar', 'estudiar', 'to study'),
      v('12-rut-almorzar', 'almorzar', 'to have lunch'),
      v('12-rut-cenar', 'cenar', 'to have dinner'),
      v('12-rut-acostarse', 'acostarse', 'to go to bed'),
      v('12-rut-levantarse', 'levantarse', 'to get up'),
      v('12-rut-vestirse', 'vestirse', 'to get dressed'),
      v('12-rut-descansar', 'descansar', 'to rest'),
      v('12-rut-cepillarse', 'cepillarse', 'to brush (teeth/hair)'),
      v('12-rut-trabajar', 'trabajar', 'to work'),
      v('12-rut-salir', 'salir', 'to go out'),
      v('12-rut-volver', 'volver', 'to return'),
      v('12-rut-dormir', 'dormir', 'to sleep'),
      v('12-rut-lavarse', 'lavarse', 'to wash oneself'),
      v('12-rut-ir', 'ir', 'to go'),
      v('12-rut-llegar', 'llegar', 'to arrive'),
      v('12-rut-empezar', 'empezar', 'to start'),
      v('12-rut-terminar', 'terminar', 'to finish'),
    ],
    'House / Casa': [
      v('12-casa-cocina', 'cocina', 'kitchen'),
      v('12-casa-dormitorio', 'dormitorio', 'bedroom'),
      v('12-casa-bano', 'baño', 'bathroom'),
      v('12-casa-jardin', 'jardín', 'garden'),
      v('12-casa-sala', 'sala', 'living room'),
      v('12-casa-ventana', 'ventana', 'window'),
      v('12-casa-puerta', 'puerta', 'door'),
      v('12-casa-techo', 'techo', 'roof / ceiling'),
      v('12-casa-mesa', 'mesa', 'table'),
      v('12-casa-silla', 'silla', 'chair'),
      v('12-casa-cama', 'cama', 'bed'),
      v('12-casa-armario', 'armario', 'wardrobe'),
      v('12-casa-piso', 'piso', 'apartment / floor'),
      v('12-casa-casa', 'casa', 'house'),
      v('12-casa-escalera', 'escalera', 'stairs'),
      v('12-casa-sofa', 'sofá', 'sofa'),
      v('12-casa-lampara', 'lámpara', 'lamp'),
      v('12-casa-nevera', 'nevera', 'fridge'),
      v('12-casa-ducha', 'ducha', 'shower'),
      v('12-casa-pasillo', 'pasillo', 'hallway'),
    ],
    'Free time / Tiempo libre': [
      v('12-ft-jugar', 'jugar', 'to play'),
      v('12-ft-nadar', 'nadar', 'to swim'),
      v('12-ft-leer', 'leer', 'to read'),
      v('12-ft-ver', 'ver', 'to watch'),
      v('12-ft-dibujar', 'dibujar', 'to draw'),
      v('12-ft-cantar', 'cantar', 'to sing'),
      v('12-ft-bailar', 'bailar', 'to dance'),
      v('12-ft-correr', 'correr', 'to run'),
      v('12-ft-viajar', 'viajar', 'to travel'),
      v('12-ft-pasear', 'pasear', 'to walk / stroll'),
      v('12-ft-deporte', 'deporte', 'sport'),
      v('12-ft-pelicula', 'película', 'film'),
      v('12-ft-musica', 'música', 'music'),
      v('12-ft-amigos', 'amigos', 'friends'),
      v('12-ft-parque', 'parque', 'park'),
      v('12-ft-cine', 'cine', 'cinema'),
      v('12-ft-futbol', 'fútbol', 'football / soccer'),
      v('12-ft-guitarra', 'guitarra', 'guitar'),
      v('12-ft-aficion', 'afición', 'hobby'),
      v('12-ft-partido', 'partido', 'match / game'),
    ],
  },
  '34': {
    'Environment / Medio ambiente': [
      v('34-env-contaminacion', 'contaminación', 'pollution'),
      v('34-env-reciclar', 'reciclar', 'to recycle'),
      v('34-env-clima', 'el cambio climático', 'climate change'),
      v('34-env-sequia', 'la sequía', 'drought'),
      v('34-env-desperdicio', 'el desperdicio', 'waste'),
      v('34-env-sostenible', 'sostenible', 'sustainable'),
      v('34-env-energia', 'la energía renovable', 'renewable energy'),
      v('34-env-calentamiento', 'el calentamiento global', 'global warming'),
      v('34-env-proteger', 'proteger', 'to protect'),
      v('34-env-recursos', 'los recursos naturales', 'natural resources'),
      v('34-env-bosque', 'el bosque', 'forest'),
      v('34-env-basura', 'la basura', 'rubbish / trash'),
      v('34-env-emisiones', 'las emisiones', 'emissions'),
      v('34-env-especie', 'la especie en peligro', 'endangered species'),
      v('34-env-plastico', 'el plástico', 'plastic'),
      v('34-env-oceano', 'el océano', 'ocean'),
      v('34-env-conciencia', 'la conciencia ambiental', 'environmental awareness'),
      v('34-env-reducir', 'reducir', 'to reduce'),
      v('34-env-huella', 'la huella de carbono', 'carbon footprint'),
      v('34-env-biodiversidad', 'la biodiversidad', 'biodiversity'),
    ],
    'Social media / Redes sociales': [
      v('34-sm-publicacion', 'la publicación', 'post'),
      v('34-sm-compartir', 'compartir', 'to share'),
      v('34-sm-seguidor', 'el seguidor', 'follower'),
      v('34-sm-subir', 'subir (una foto)', 'to upload (a photo)'),
      v('34-sm-influencer', 'el influencer', 'influencer'),
      v('34-sm-privacidad', 'la privacidad', 'privacy'),
      v('34-sm-ciberacoso', 'el ciberacoso', 'cyberbullying'),
      v('34-sm-pantalla', 'la pantalla', 'screen'),
      v('34-sm-desconexion', 'la desconexión digital', 'digital detox'),
      v('34-sm-viral', 'viral', 'viral'),
      v('34-sm-comentario', 'el comentario', 'comment'),
      v('34-sm-perfil', 'el perfil', 'profile'),
      v('34-sm-noticia', 'la noticia falsa', 'fake news'),
      v('34-sm-comparar', 'compararse', 'to compare oneself'),
      v('34-sm-algoritmo', 'el algoritmo', 'algorithm'),
      v('34-sm-mensaje', 'el mensaje', 'message'),
      v('34-sm-bloquear', 'bloquear', 'to block'),
      v('34-sm-adiccion', 'la adicción', 'addiction'),
      v('34-sm-identidad', 'la identidad digital', 'digital identity'),
      v('34-sm-tendencia', 'la tendencia', 'trend'),
    ],
    'Health & wellbeing / Salud': [
      v('34-h-estres', 'el estrés', 'stress'),
      v('34-h-alimentacion', 'la alimentación sana', 'healthy eating'),
      v('34-h-bienestar', 'el bienestar', 'wellbeing'),
      v('34-h-ejercicio', 'hacer ejercicio', 'to exercise'),
      v('34-h-ansiedad', 'la ansiedad', 'anxiety'),
      v('34-h-dormir', 'dormir bien', 'to sleep well'),
      v('34-h-equilibrado', 'equilibrado', 'balanced'),
      v('34-h-mental', 'la salud mental', 'mental health'),
      v('34-h-relajarse', 'relajarse', 'to relax'),
      v('34-h-habito', 'el hábito', 'habit'),
      v('34-h-sueno', 'el sueño', 'sleep / dream'),
      v('34-h-presion', 'la presión', 'pressure'),
      v('34-h-descanso', 'el descanso', 'rest'),
      v('34-h-autoestima', 'la autoestima', 'self-esteem'),
      v('34-h-meditar', 'meditar', 'to meditate'),
      v('34-h-enfermedad', 'la enfermedad', 'illness'),
      v('34-h-prevencion', 'la prevención', 'prevention'),
      v('34-h-hidratarse', 'hidratarse', 'to stay hydrated'),
      v('34-h-equilibrio', 'el equilibrio', 'balance'),
      v('34-h-apoyo', 'el apoyo', 'support'),
    ],
    'Travel & culture / Viajes y cultura': [
      v('34-tr-intercambio', 'el intercambio cultural', 'cultural exchange'),
      v('34-tr-costumbre', 'la costumbre', 'custom'),
      v('34-tr-patrimonio', 'el patrimonio', 'heritage'),
      v('34-tr-alojamiento', 'el alojamiento', 'accommodation'),
      v('34-tr-explorar', 'explorar', 'to explore'),
      v('34-tr-identidad', 'la identidad', 'identity'),
      v('34-tr-diversidad', 'la diversidad', 'diversity'),
      v('34-tr-idioma', 'el idioma', 'language'),
      v('34-tr-tradicion', 'la tradición', 'tradition'),
      v('34-tr-extranjero', 'el extranjero', 'abroad / foreigner'),
      v('34-tr-viaje', 'el viaje', 'trip'),
      v('34-tr-frontera', 'la frontera', 'border'),
      v('34-tr-guia', 'la guía', 'guide'),
      v('34-tr-destino', 'el destino', 'destination'),
      v('34-tr-adaptarse', 'adaptarse', 'to adapt'),
      v('34-tr-estereotipo', 'el estereotipo', 'stereotype'),
      v('34-tr-hospitalidad', 'la hospitalidad', 'hospitality'),
      v('34-tr-maleta', 'la maleta', 'suitcase'),
      v('34-tr-cultura', 'la cultura', 'culture'),
      v('34-tr-conocer', 'conocer gente', 'to meet people'),
    ],
    'Global issues / Problemas globales': [
      v('34-gl-desigualdad', 'la desigualdad', 'inequality'),
      v('34-gl-pobreza', 'la pobreza', 'poverty'),
      v('34-gl-derechos', 'los derechos humanos', 'human rights'),
      v('34-gl-globalizacion', 'la globalización', 'globalization'),
      v('34-gl-conflicto', 'el conflicto', 'conflict'),
      v('34-gl-migracion', 'la migración', 'migration'),
      v('34-gl-solidaridad', 'la solidaridad', 'solidarity'),
      v('34-gl-voluntariado', 'el voluntariado', 'volunteering'),
      v('34-gl-injusticia', 'la injusticia', 'injustice'),
      v('34-gl-ong', 'la ONG', 'NGO'),
      v('34-gl-paz', 'la paz', 'peace'),
      v('34-gl-refugiado', 'el refugiado', 'refugee'),
      v('34-gl-educacion', 'el acceso a la educación', 'access to education'),
      v('34-gl-discriminacion', 'la discriminación', 'discrimination'),
      v('34-gl-campana', 'la campaña', 'campaign'),
      v('34-gl-conciencia', 'concienciar', 'to raise awareness'),
      v('34-gl-cooperacion', 'la cooperación', 'cooperation'),
      v('34-gl-hambre', 'el hambre', 'hunger (famine)'),
      v('34-gl-igualdad', 'la igualdad', 'equality'),
      v('34-gl-justicia', 'la justicia social', 'social justice'),
    ],
    'Careers & future / Carreras y futuro': [
      v('34-ca-meta', 'la meta', 'goal'),
      v('34-ca-objetivo', 'el objetivo', 'objective'),
      v('34-ca-carrera', 'la carrera universitaria', 'university degree'),
      v('34-ca-emprendimiento', 'el emprendimiento', 'entrepreneurship'),
      v('34-ca-practicas', 'las prácticas', 'internship'),
      v('34-ca-vocacion', 'la vocación', 'vocation'),
      v('34-ca-decision', 'tomar una decisión', 'to make a decision'),
      v('34-ca-desafio', 'el desafío', 'challenge'),
      v('34-ca-oportunidad', 'la oportunidad', 'opportunity'),
      v('34-ca-superar', 'superar', 'to overcome'),
      v('34-ca-futuro', 'el futuro', 'future'),
      v('34-ca-profesion', 'la profesión', 'profession'),
      v('34-ca-entrevista', 'la entrevista', 'interview'),
      v('34-ca-curriculum', 'el currículum', 'CV / résumé'),
      v('34-ca-habilidad', 'la habilidad', 'skill'),
      v('34-ca-sueno', 'el sueño', 'dream'),
      v('34-ca-planificar', 'planificar', 'to plan'),
      v('34-ca-responsable', 'responsable', 'responsible'),
      v('34-ca-experiencia', 'la experiencia', 'experience'),
      v('34-ca-universidad', 'la universidad', 'university'),
    ],
  },
};

function gq(id, sentence, opts, correct) {
  return { id, sentence, opts, correct };
}

export const grammarSetsByLevel = {
  '12': {
    'Ser vs Estar': {
      explain: 'Use <strong>ser</strong> for permanent traits/identity, <strong>estar</strong> for temporary states/location.',
      production: 'Escribe una frase con <strong>estar</strong> + un lugar (por ejemplo: Yo estoy en la cocina).',
      qs: [
        gq('12-se-1', 'Yo ___ estudiante.', ['soy', 'estoy'], 'soy'),
        gq('12-se-2', 'Ella ___ cansada hoy.', ['es', 'está'], 'está'),
        gq('12-se-3', 'Nosotros ___ de Noruega.', ['somos', 'estamos'], 'somos'),
        gq('12-se-4', 'El café ___ caliente.', ['es', 'está'], 'está'),
        gq('12-se-5', 'Tú ___ muy alto.', ['eres', 'estás'], 'eres'),
        gq('12-se-6', '¿Dónde ___ el baño?', ['es', 'está'], 'está'),
        gq('12-se-7', 'Ellos ___ felices.', ['son', 'están'], 'están'),
        gq('12-se-8', 'Mi hermano ___ médico.', ['es', 'está'], 'es'),
        gq('12-se-9', 'La fiesta ___ en mi casa.', ['es', 'está'], 'es'),
        gq('12-se-10', 'Yo ___ en la escuela ahora.', ['soy', 'estoy'], 'estoy'),
        gq('12-se-11', 'Hoy ___ lunes.', ['es', 'está'], 'es'),
        gq('12-se-12', 'Las manzanas ___ verdes y ácidas.', ['son', 'están'], 'son'),
        gq('12-se-13', 'Mis padres ___ en el jardín.', ['son', 'están'], 'están'),
        gq('12-se-14', 'Esa película ___ aburrida.', ['es', 'está'], 'es'),
      ],
    },
    'Present tense -AR verbs': {
      explain: 'Regular -ar verbs: habl<strong>ar</strong> → hablo, hablas, habla, hablamos, habláis, hablan.',
      production: 'Escribe una frase en presente con un verbo -ar (hablar, estudiar, bailar…).',
      qs: [
        gq('12-ar-1', 'Yo ___ (hablar) español.', ['hablo', 'habla'], 'hablo'),
        gq('12-ar-2', 'Tú ___ (estudiar) mucho.', ['estudias', 'estudia'], 'estudias'),
        gq('12-ar-3', 'Ella ___ (bailar) muy bien.', ['bailo', 'baila'], 'baila'),
        gq('12-ar-4', 'Nosotros ___ (cantar) juntos.', ['cantamos', 'cantáis'], 'cantamos'),
        gq('12-ar-5', 'Ellos ___ (jugar) fútbol.', ['juega', 'juegan'], 'juegan'),
        gq('12-ar-6', 'Yo ___ (mirar) la tele.', ['miro', 'mira'], 'miro'),
        gq('12-ar-7', 'Tú ___ (trabajar) hoy.', ['trabajo', 'trabajas'], 'trabajas'),
        gq('12-ar-8', 'Él ___ (cocinar) la cena.', ['cocina', 'cocino'], 'cocina'),
        gq('12-ar-9', 'Vosotros ___ (caminar) rápido.', ['caminan', 'camináis'], 'camináis'),
        gq('12-ar-10', 'Yo ___ (necesitar) ayuda.', ['necesito', 'necesita'], 'necesito'),
        gq('12-ar-11', 'Nosotros ___ (llegar) a las ocho.', ['llegamos', 'llegan'], 'llegamos'),
        gq('12-ar-12', 'Ella ___ (escuchar) música.', ['escucha', 'escucho'], 'escucha'),
        gq('12-ar-13', 'Tú ___ (comprar) pan.', ['compras', 'compra'], 'compras'),
        gq('12-ar-14', 'Ellos ___ (estudiar) para el examen.', ['estudian', 'estudiamos'], 'estudian'),
      ],
    },
    'Possessive adjectives': {
      explain: 'mi/mis, tu/tus, su/sus agree in number (not gender) with the noun that follows.',
      production: 'Escribe dos frases: una con <strong>mi</strong> y otra con <strong>mis</strong>.',
      qs: [
        gq('12-po-1', '___ madre es profesora. (my)', ['mi', 'mis'], 'mi'),
        gq('12-po-2', '¿Dónde están ___ libros? (your)', ['tu', 'tus'], 'tus'),
        gq('12-po-3', 'Ellos tienen ___ mochila. (their)', ['su', 'sus'], 'su'),
        gq('12-po-4', '___ perros son grandes. (my)', ['mi', 'mis'], 'mis'),
        gq('12-po-5', '¿Es ___ casa? (your)', ['tu', 'tus'], 'tu'),
        gq('12-po-6', 'Ella busca ___ llaves. (her)', ['su', 'sus'], 'sus'),
        gq('12-po-7', '___ amigos viven aquí. (our)', ['nuestro', 'nuestros'], 'nuestros'),
        gq('12-po-8', '___ hermana estudia arte. (my)', ['mi', 'mis'], 'mi'),
        gq('12-po-9', 'Tienen ___ propio coche. (their)', ['su', 'sus'], 'su'),
        gq('12-po-10', '¿Tienes ___ tarea? (your)', ['tu', 'tus'], 'tu'),
        gq('12-po-11', '___ profesora es simpática. (our)', ['nuestra', 'nuestras'], 'nuestra'),
        gq('12-po-12', 'Voy a ___ colegio. (my)', ['mi', 'mis'], 'mi'),
        gq('12-po-13', '___ ventanas son grandes. (our)', ['nuestra', 'nuestras'], 'nuestras'),
        gq('12-po-14', 'Él lleva ___ mochila azul. (his)', ['su', 'sus'], 'su'),
      ],
    },
  },
  '34': {
    'Preterite vs Imperfect': {
      explain: 'Use the <strong>preterite</strong> for completed actions, the <strong>imperfect</strong> for ongoing/habitual past actions or descriptions.',
      production: 'Escribe dos frases sobre ayer: una en pretérito y otra en imperfecto.',
      qs: [
        gq('34-pi-1', 'Ayer ___ (comer) paella.', ['comí', 'comía'], 'comí'),
        gq('34-pi-2', 'Cuando era niño, ___ (jugar) mucho fútbol.', ['jugué', 'jugaba'], 'jugaba'),
        gq('34-pi-3', 'El año pasado ___ (viajar) a España.', ['viajé', 'viajaba'], 'viajé'),
        gq('34-pi-4', 'Mientras yo ___ (estudiar), mi hermano veía la tele.', ['estudié', 'estudiaba'], 'estudiaba'),
        gq('34-pi-5', 'De repente, ___ (empezar) a llover.', ['empezó', 'empezaba'], 'empezó'),
        gq('34-pi-6', 'Todos los días ella ___ (caminar) al colegio.', ['caminó', 'caminaba'], 'caminaba'),
        gq('34-pi-7', 'El sábado ___ (ver) una película.', ['vi', 'veía'], 'vi'),
        gq('34-pi-8', 'Antes yo ___ (vivir) en Madrid.', ['viví', 'vivía'], 'vivía'),
        gq('34-pi-9', 'Ellos ___ (llegar) tarde ayer.', ['llegaron', 'llegaban'], 'llegaron'),
        gq('34-pi-10', 'Normalmente nosotros ___ (desayunar) a las ocho.', ['desayunamos', 'desayunábamos'], 'desayunábamos'),
        gq('34-pi-11', 'Cuando salimos, todavía ___ (llover).', ['llovió', 'llovía'], 'llovía'),
        gq('34-pi-12', 'El verano pasado ___ (conocer) a mis primos.', ['conocí', 'conocía'], 'conocí'),
        gq('34-pi-13', 'En aquella época, la casa ___ (ser) pequeña.', ['fue', 'era'], 'era'),
        gq('34-pi-14', 'Ayer a las cinco ___ (terminar) la tarea.', ['terminé', 'terminaba'], 'terminé'),
        gq('34-pi-15', 'Siempre ___ (haber) mucha gente en la plaza.', ['hubo', 'había'], 'había'),
      ],
    },
    'Subjunctive (present)': {
      explain: 'Use the subjunctive after expressions of wish, doubt, emotion, or "que" clauses expressing opinion/desire.',
      production: 'Escribe una frase con <strong>espero que</strong> + subjuntivo.',
      qs: [
        gq('34-su-1', 'Espero que tú ___ (venir) a la fiesta.', ['vienes', 'vengas'], 'vengas'),
        gq('34-su-2', 'Es importante que nosotros ___ (reciclar).', ['reciclamos', 'reciclemos'], 'reciclemos'),
        gq('34-su-3', 'Ojalá que ella ___ (aprobar) el examen.', ['aprueba', 'apruebe'], 'apruebe'),
        gq('34-su-4', 'No creo que él ___ (tener) razón.', ['tiene', 'tenga'], 'tenga'),
        gq('34-su-5', 'Quiero que ustedes ___ (estudiar) más.', ['estudian', 'estudien'], 'estudien'),
        gq('34-su-6', 'Dudo que ellos ___ (llegar) a tiempo.', ['llegan', 'lleguen'], 'lleguen'),
        gq('34-su-7', 'Es posible que ___ (llover) mañana.', ['llueve', 'llueva'], 'llueva'),
        gq('34-su-8', 'Me alegra que tú ___ (estar) aquí.', ['estás', 'estés'], 'estés'),
        gq('34-su-9', 'Necesito que alguien me ___ (ayudar).', ['ayuda', 'ayude'], 'ayude'),
        gq('34-su-10', 'Es raro que ella no ___ (contestar).', ['contesta', 'conteste'], 'conteste'),
        gq('34-su-11', 'Prefiero que vosotros ___ (venir) mañana.', ['venís', 'vengáis'], 'vengáis'),
        gq('34-su-12', 'No es cierto que eso ___ (ser) fácil.', ['es', 'sea'], 'sea'),
        gq('34-su-13', 'Te aconsejo que ___ (hablar) con el profesor.', ['hablas', 'hables'], 'hables'),
        gq('34-su-14', 'Es necesario que la gente ___ (proteger) el planeta.', ['protege', 'proteja'], 'proteja'),
      ],
    },
    'Comparatives & superlatives': {
      explain: 'más...que / menos...que for comparisons; el/la más...de for superlatives. Irregular: mejor, peor, mayor, menor.',
      production: 'Compara dos asignaturas usando <strong>más...que</strong> o <strong>menos...que</strong>.',
      qs: [
        gq('34-co-1', 'Este libro es ___ interesante que el otro. (more)', ['más', 'menos'], 'más'),
        gq('34-co-2', 'Ella es la ___ inteligente de la clase. (most)', ['más', 'menor'], 'más'),
        gq('34-co-3', 'Mi hermano es ___ que yo. (older)', ['mayor', 'menor'], 'mayor'),
        gq('34-co-4', 'Este examen es ___ difícil que el anterior. (less)', ['menos', 'más'], 'menos'),
        gq('34-co-5', 'Es el ___ restaurante de la ciudad. (best)', ['mejor', 'peor'], 'mejor'),
        gq('34-co-6', 'Tu nota es ___ que la mía. (worse)', ['peor', 'mejor'], 'peor'),
        gq('34-co-7', 'Tiene tanto dinero ___ tú. (as...as)', ['como', 'que'], 'como'),
        gq('34-co-8', 'Este coche es tan rápido ___ aquel.', ['como', 'que'], 'como'),
        gq('34-co-9', 'Ella es la ___ joven de la familia. (youngest)', ['menor', 'mayor'], 'menor'),
        gq('34-co-10', 'Mi ciudad es ___ grande que Madrid. (less)', ['menos', 'más'], 'menos'),
        gq('34-co-11', 'Hoy hace ___ frío que ayer. (more)', ['más', 'menos'], 'más'),
        gq('34-co-12', 'Es la película ___ divertida del año. (most)', ['más', 'mejor'], 'más'),
        gq('34-co-13', 'Este ejercicio es tan fácil ___ el primero.', ['como', 'que'], 'como'),
        gq('34-co-14', 'Para mí, el inglés es ___ difícil que el español. (less)', ['menos', 'peor'], 'menos'),
      ],
    },
  },
};

export const listeningItemsByLevel = {
  '12': [
    {
      id: '12-l1',
      text: 'Mi familia tiene cuatro personas: mi madre, mi padre, mi hermana y yo.',
      visual: 'A framed family photo on a shelf: two adults and two children.',
      qs: [
        { q: 'How many people are in the family?', opts: ['Three', 'Four', 'Five'], correct: 'Four', type: 'detail' },
        { q: 'What is the main idea of the clip?', opts: ['The speaker describes their family', 'The speaker talks about school', 'The speaker orders food'], correct: 'The speaker describes their family', type: 'main' },
      ],
    },
    {
      id: '12-l2',
      text: 'Todos los días me despierto a las siete y desayuno pan con queso.',
      visual: 'A kitchen table with bread, cheese, and a glass of juice.',
      qs: [
        { q: 'What does the speaker eat for breakfast?', opts: ['Fruit', 'Bread with cheese', 'Rice'], correct: 'Bread with cheese', type: 'detail' },
        { q: 'When do they wake up?', opts: ['At six', 'At seven', 'At eight'], correct: 'At seven', type: 'detail' },
      ],
    },
    {
      id: '12-l3',
      text: 'Los fines de semana me gusta nadar y jugar al fútbol con mis amigos.',
      visual: 'Friends with a football near a swimming pool.',
      qs: [
        { q: 'What activities does the speaker enjoy on weekends?', opts: ['Reading and drawing', 'Swimming and football', 'Cooking and dancing'], correct: 'Swimming and football', type: 'detail' },
        { q: 'Who do they play football with?', opts: ['Their teacher', 'Their friends', 'Their grandparents'], correct: 'Their friends', type: 'detail' },
      ],
    },
    {
      id: '12-l4',
      text: 'Mi casa tiene un jardín grande con muchas flores y un árbol viejo.',
      visual: 'A house garden with flowers and an old tree.',
      qs: [
        { q: 'What is in the garden?', opts: ['A pool', 'Flowers and an old tree', 'A garage'], correct: 'Flowers and an old tree', type: 'detail' },
        { q: 'How is the garden described?', opts: ['Small', 'Large', 'Empty'], correct: 'Large', type: 'detail' },
      ],
    },
    {
      id: '12-l5',
      text: 'En la escuela mi clase favorita es la de arte porque me gusta dibujar.',
      visual: 'A classroom with drawings on the wall.',
      qs: [
        { q: 'Why does the speaker like art class?', opts: ['They like drawing', 'It is easy', 'The teacher is nice'], correct: 'They like drawing', type: 'detail' },
        { q: 'What is the main idea?', opts: ['The speaker explains a favourite school subject', 'The speaker describes their house', 'The speaker talks about dinner'], correct: 'The speaker explains a favourite school subject', type: 'main' },
      ],
    },
    {
      id: '12-l6',
      text: 'Por la tarde hago la tarea en mi dormitorio y luego ceno con mi familia a las siete.',
      visual: 'A desk with a notebook, then a family dinner table.',
      qs: [
        { q: 'Where does the speaker do homework?', opts: ['In the kitchen', 'In the bedroom', 'At school'], correct: 'In the bedroom', type: 'detail' },
        { q: 'What happens at seven?', opts: ['They go to bed', 'They have dinner with family', 'They play football'], correct: 'They have dinner with family', type: 'detail' },
      ],
    },
    {
      id: '12-l7',
      text: 'Los sábados voy al parque con mi perro. Me gusta pasear y jugar con la pelota.',
      visual: 'A dog and a ball in a park.',
      qs: [
        { q: 'When does the speaker go to the park?', opts: ['On Mondays', 'On Saturdays', 'Every night'], correct: 'On Saturdays', type: 'detail' },
        { q: 'Who goes with the speaker?', opts: ['A brother', 'A dog', 'A teacher'], correct: 'A dog', type: 'detail' },
      ],
    },
    {
      id: '12-l8',
      text: 'En el comedor del colegio como arroz, verduras y a veces pollo. Bebo agua, no zumo.',
      visual: 'A school cafeteria tray with rice and vegetables.',
      qs: [
        { q: 'What does the speaker drink?', opts: ['Juice', 'Water', 'Milk'], correct: 'Water', type: 'detail' },
        { q: 'Where do they eat this meal?', opts: ['At home', 'In the school cafeteria', 'In a restaurant'], correct: 'In the school cafeteria', type: 'detail' },
      ],
    },
    {
      id: '12-l9',
      text: 'Mi abuela vive cerca. Los domingos visitamos su casa y ella cocina una sopa muy buena.',
      visual: 'An older woman serving soup at a table.',
      qs: [
        { q: 'When do they visit grandmother?', opts: ['On Sundays', 'On Fridays', 'Every morning'], correct: 'On Sundays', type: 'detail' },
        { q: 'What does grandmother cook?', opts: ['Pizza', 'Soup', 'Salad'], correct: 'Soup', type: 'detail' },
      ],
    },
    {
      id: '12-l10',
      text: 'Hoy tengo un examen de español. Estudio con mi cuaderno y un lápiz en la biblioteca.',
      visual: 'A student at a library desk with a notebook.',
      qs: [
        { q: 'What exam does the speaker have today?', opts: ['Maths', 'Spanish', 'Art'], correct: 'Spanish', type: 'detail' },
        { q: 'Where are they studying?', opts: ['In the garden', 'In the library', 'At a café'], correct: 'In the library', type: 'detail' },
      ],
    },
  ],
  '34': [
    {
      id: '34-l1',
      text: 'El cambio climático es uno de los problemas más graves que enfrenta el mundo hoy, y muchos jóvenes piden acciones urgentes a los gobiernos.',
      visual: 'A protest poster about climate action.',
      qs: [
        { q: 'What are young people asking governments to do?', opts: ['Build more schools', 'Take urgent action on climate change', 'Lower taxes'], correct: 'Take urgent action on climate change', type: 'detail' },
        { q: 'How is climate change described?', opts: ['A small local issue', 'One of the most serious problems in the world today', 'A problem that is already solved'], correct: 'One of the most serious problems in the world today', type: 'main' },
      ],
    },
    {
      id: '34-l2',
      text: 'Aunque las redes sociales nos conectan con amigos, también pueden causar ansiedad si pasamos demasiado tiempo comparándonos con otros.',
      visual: 'A phone screen with likes next to a worried face.',
      qs: [
        { q: 'What can cause anxiety according to the speaker?', opts: ['Not having a phone', 'Spending too much time comparing yourself to others online', 'Having too many friends'], correct: 'Spending too much time comparing yourself to others online', type: 'detail' },
        { q: 'What positive point is mentioned?', opts: ['Social media connects us with friends', 'Social media always improves sleep', 'Social media replaces school'], correct: 'Social media connects us with friends', type: 'main' },
      ],
    },
    {
      id: '34-l3',
      text: 'Durante mi año de intercambio en Argentina, aprendí muchísimo sobre otra cultura y mejoré mucho mi español.',
      visual: 'A suitcase and a map of Argentina.',
      qs: [
        { q: 'What did the speaker do during their exchange year?', opts: ['Learned about another culture and improved their Spanish', 'Studied only English', 'Stayed home the whole year'], correct: 'Learned about another culture and improved their Spanish', type: 'main' },
        { q: 'Where did the exchange take place?', opts: ['Mexico', 'Argentina', 'Spain'], correct: 'Argentina', type: 'detail' },
      ],
    },
    {
      id: '34-l4',
      text: 'Muchas organizaciones no gubernamentales trabajan para reducir la pobreza y mejorar el acceso a la educación en países en desarrollo.',
      visual: 'A classroom in a community centre with an NGO banner.',
      qs: [
        { q: 'What do these NGOs work to reduce and improve?', opts: ['Reduce pollution and improve traffic', 'Reduce poverty and improve access to education', 'Reduce prices and improve tourism'], correct: 'Reduce poverty and improve access to education', type: 'detail' },
        { q: 'Where is this work focused, according to the clip?', opts: ['Only in Europe', 'In developing countries', 'Only online'], correct: 'In developing countries', type: 'detail' },
      ],
    },
    {
      id: '34-l5',
      text: 'Antes de elegir una carrera universitaria, es importante reflexionar sobre tus intereses y tus objetivos a largo plazo.',
      visual: 'A student looking at university brochures.',
      qs: [
        { q: 'What should you reflect on before choosing a university degree?', opts: ["Your friends' choices", 'Your interests and long-term goals', 'The cheapest option'], correct: 'Your interests and long-term goals', type: 'main' },
        { q: 'When should this reflection happen?', opts: ['After graduating', 'Before choosing a degree', 'During the first exam'], correct: 'Before choosing a degree', type: 'detail' },
      ],
    },
    {
      id: '34-l6',
      text: 'Para cuidar la salud mental, muchos jóvenes recomiendan dormir bien, hacer ejercicio y hablar con alguien de confianza cuando hay estrés.',
      visual: 'Icons for sleep, sport, and a conversation.',
      qs: [
        { q: 'Which three recommendations are mentioned?', opts: ['Sleep well, exercise, and talk to someone you trust', 'Study all night, drink coffee, and stay silent', 'Travel more, buy clothes, and use more social media'], correct: 'Sleep well, exercise, and talk to someone you trust', type: 'detail' },
        { q: 'What is the main purpose of the clip?', opts: ['To advertise a product', 'To suggest ways to look after mental health', 'To explain a grammar rule'], correct: 'To suggest ways to look after mental health', type: 'main' },
      ],
    },
    {
      id: '34-l7',
      text: 'El turismo puede ayudar a la economía local, pero si no es sostenible, también daña el patrimonio y genera demasiada basura.',
      visual: 'A historic square crowded with tourists and litter.',
      qs: [
        { q: 'What positive effect of tourism is mentioned?', opts: ['It can help the local economy', 'It always protects nature', 'It reduces inequality'], correct: 'It can help the local economy', type: 'detail' },
        { q: 'What problems appear if tourism is not sustainable?', opts: ['It damages heritage and creates too much rubbish', 'It makes language learning impossible', 'It lowers the temperature'], correct: 'It damages heritage and creates too much rubbish', type: 'detail' },
      ],
    },
    {
      id: '34-l8',
      text: 'En mi opinión, bloquear a una persona que practica ciberacoso no es suficiente: las escuelas deben concienciar sobre la privacidad y el respeto.',
      visual: 'A school workshop poster about online respect.',
      qs: [
        { q: 'What does the speaker say is not enough on its own?', opts: ['Blocking someone who cyberbullies', 'Deleting all apps', 'Leaving school'], correct: 'Blocking someone who cyberbullies', type: 'detail' },
        { q: 'What should schools raise awareness about?', opts: ['Privacy and respect', 'Sports results', 'Fashion trends'], correct: 'Privacy and respect', type: 'main' },
      ],
    },
    {
      id: '34-l9',
      text: 'El verano pasado hice prácticas en una biblioteca. Al principio tenía miedo, pero superé el desafío y gané mucha experiencia.',
      visual: 'A teenager shelving books in a library.',
      qs: [
        { q: 'Where did the speaker intern last summer?', opts: ['In a hospital', 'In a library', 'In a restaurant'], correct: 'In a library', type: 'detail' },
        { q: 'How did their feelings change?', opts: ['They were afraid at first but overcame the challenge', 'They were bored the whole time', 'They quit after one day'], correct: 'They were afraid at first but overcame the challenge', type: 'main' },
      ],
    },
    {
      id: '34-l10',
      text: 'La migración no es solo un problema: muchas personas buscan paz, trabajo o educación, y la solidaridad de la comunidad es fundamental.',
      visual: 'A community welcome sign in several languages.',
      qs: [
        { q: 'According to the speaker, why do many people migrate?', opts: ['Only for holidays', 'To look for peace, work, or education', 'Because they dislike languages'], correct: 'To look for peace, work, or education', type: 'detail' },
        { q: 'What attitude does the speaker present as essential?', opts: ['Community solidarity', 'Ignoring the topic', 'Closing all borders immediately'], correct: 'Community solidarity', type: 'main' },
      ],
    },
  ],
};

export const readingItemsByLevel = {
  '12': [
    {
      id: '12-r1',
      title: 'Una nota en la cocina',
      visual: 'A sticky note on a fridge door.',
      text: 'Hola Ana: Hoy llego tarde porque tengo una reunión. Hay pan y queso en la nevera para la cena, y también una ensalada. Por favor, saca al perro al jardín a las seis y dale agua. Tu hermano está en su dormitorio estudiando para un examen de matemáticas, así que no pongas la música muy alta. Si tienes hambre antes, puedes comer una manzana. Besos, Mamá. P.D. Tu padre vuelve a las ocho.',
      qs: [
        { q: 'What is the main purpose of this text?', opts: ['To leave family instructions', 'To advertise a restaurant', 'To describe a holiday'], correct: 'To leave family instructions', type: 'purpose' },
        { q: 'What should Ana do at six?', opts: ['Cook chicken', 'Take the dog to the garden', 'Go to school'], correct: 'Take the dog to the garden', type: 'detail' },
        { q: 'Where is Ana’s brother?', opts: ['In the garden', 'In his bedroom studying', 'At football'], correct: 'In his bedroom studying', type: 'detail' },
      ],
      responsePrompt: '¿Dejas notas en casa? ¿Qué escribes normalmente?',
    },
    {
      id: '12-r2',
      title: 'Mi rutina de lunes',
      visual: 'A simple timetable sketched in a notebook.',
      text: 'Los lunes me levanto a las siete. Me ducho, me visto y desayuno leche y una manzana. Después voy al colegio en autobús con mi hermana. Tengo matemáticas, español y arte. En el recreo hablo con mis amigos en el patio. Por la tarde hago la tarea en mi pupitre, ceno con mi familia y a las nueve me acuesto. No me gusta el lunes, pero me gusta el arte porque dibujo mucho.',
      qs: [
        { q: 'What is the main idea?', opts: ['A description of a Monday routine', 'A menu for a party', 'Rules for a sport'], correct: 'A description of a Monday routine', type: 'main' },
        { q: 'How does the writer go to school?', opts: ['By car', 'By bus', 'On foot'], correct: 'By bus', type: 'detail' },
        { q: 'Which subjects are mentioned?', opts: ['Maths, Spanish and art', 'History and music only', 'Only sport'], correct: 'Maths, Spanish and art', type: 'detail' },
      ],
      responsePrompt: '¿Tu lunes es parecido o diferente? Escribe dos frases.',
    },
    {
      id: '12-r3',
      title: 'Cartel del comedor',
      visual: 'A colourful cafeteria poster with food drawings.',
      text: 'Comedor del colegio — menú del martes. Primero: sopa de verduras. Segundo: pollo con arroz o ensalada con queso. Postre: fruta (manzana o naranja). Bebida: agua. Recuerda: no hay zumo esta semana. El almuerzo es a las doce y media. Si tienes alergia, habla con el profesor. Trae tu botella de agua. Los alumnos de primero comen antes. ¡Buen provecho y no dejes basura en la mesa!',
      qs: [
        { q: 'What type of text is this?', opts: ['A school cafeteria menu poster', 'A personal diary', 'A train ticket'], correct: 'A school cafeteria menu poster', type: 'purpose' },
        { q: 'What can you drink?', opts: ['Juice', 'Water', 'Milkshake'], correct: 'Water', type: 'detail' },
        { q: 'When is lunch?', opts: ['At 12:30', 'At 7:00', 'At 16:00'], correct: 'At 12:30', type: 'detail' },
      ],
      responsePrompt: '¿Qué eliges tú del menú y por qué?',
    },
    {
      id: '12-r4',
      title: 'Mensaje de Lucía',
      visual: 'A phone message bubble.',
      text: 'Hola, ¿qué tal? ¿Quieres ir al cine el sábado? Hay una película divertida a las cinco cerca del parque. Después podemos pasear o tomar un zumo. Si llueve, vamos a mi casa: hay una guitarra y podemos cantar. Mi madre cocina pizza y mi hermano también está. Respóndeme, por favor, porque necesito comprar las entradas mañana. ¿Vienes en autobús o te recoge tu padre? ¡Hasta pronto! Lucía',
      qs: [
        { q: 'What does Lucía want to do?', opts: ['Go to the cinema on Saturday', 'Study for an exam tonight', 'Cook dinner on Sunday'], correct: 'Go to the cinema on Saturday', type: 'main' },
        { q: 'What is the backup plan if it rains?', opts: ['Cancel everything', 'Go to Lucía’s house and play', 'Go swimming'], correct: 'Go to Lucía’s house and play', type: 'detail' },
        { q: 'What is the purpose of the message?', opts: ['To invite a friend and ask for a reply', 'To sell tickets', 'To describe a house'], correct: 'To invite a friend and ask for a reply', type: 'purpose' },
      ],
      responsePrompt: '¿Aceptas la invitación? Escribe tu respuesta en español.',
    },
    {
      id: '12-r5',
      title: 'Mi casa',
      visual: 'A child’s drawing of a house with labels.',
      text: 'Vivo en un piso pequeño cerca del colegio. Hay una cocina, una sala, un baño y dos dormitorios. Mi habitación tiene una cama, un armario, una lámpara y una ventana grande. Me gusta leer en la sala porque hay un sofá cómodo y una mesa. El jardín es de los vecinos, pero a veces jugamos allí con una pelota. Por la noche, la casa está tranquila. Mi mascota duerme en el pasillo.',
      qs: [
        { q: 'Where does the writer live?', opts: ['In a small apartment', 'In a hotel', 'On a farm'], correct: 'In a small apartment', type: 'main' },
        { q: 'Why do they like the living room?', opts: ['There is a comfortable sofa for reading', 'There is a swimming pool', 'It has three kitchens'], correct: 'There is a comfortable sofa for reading', type: 'detail' },
        { q: 'Whose garden is it?', opts: ['The neighbours’', 'The school’s', 'The writer’s grandparents’'], correct: 'The neighbours’', type: 'detail' },
      ],
      responsePrompt: 'Describe una habitación de tu casa en tres frases.',
    },
    {
      id: '12-r6',
      title: 'Anuncio del club de deporte',
      visual: 'A flyer with a football and a swimming icon.',
      text: 'Club escolar de deporte. Los martes: fútbol en el parque a las cuatro. Los jueves: natación en la piscina a las cinco. Necesitas una mochila, agua y ganas de jugar. El primer día es gratis. Habla con el profesor de educación física en el recreo. También hay un grupo de carrera los viernes, pero es opcional. Ven con amigos: es más divertido y practicamos español después del partido.',
      qs: [
        { q: 'What is this text for?', opts: ['To advertise a school sports club', 'To explain a grammar point', 'To give a cooking recipe'], correct: 'To advertise a school sports club', type: 'purpose' },
        { q: 'When is swimming?', opts: ['Tuesday at 16:00', 'Thursday at 17:00', 'Sunday at 10:00'], correct: 'Thursday at 17:00', type: 'detail' },
        { q: 'What do you need to bring?', opts: ['A backpack, water and energy to play', 'A computer and a dictionary', 'Only a ticket'], correct: 'A backpack, water and energy to play', type: 'detail' },
      ],
      responsePrompt: '¿Te interesa el club? ¿Qué deporte prefieres?',
    },
  ],
  '34': [
    {
      id: '34-r1',
      title: 'Carta al periódico local',
      visual: 'A newspaper letters page with an environment headline.',
      text: 'Estimado director: Escribo porque en nuestro barrio hay demasiado plástico en las calles y las emisiones de los coches son altas los días de colegio. El cambio climático no es un problema lejano: la sequía ya afecta a los parques y hay menos biodiversidad. Propongo más contenedores de reciclaje, talleres en el colegio para reducir el desperdicio y carriles para bicicletas. Es necesario que el ayuntamiento actúe este año. Si no protegemos los recursos naturales ahora, el calentamiento global será peor para las próximas generaciones. Muchos jóvenes queremos ayudar, pero necesitamos organización y ejemplos claros. Atentamente, Marina López, 15 años.',
      qs: [
        { q: 'What is the writer’s main purpose?', opts: ['To propose local environmental action', 'To review a film', 'To apply for a job'], correct: 'To propose local environmental action', type: 'purpose' },
        { q: 'Which local problem is mentioned first?', opts: ['Too much plastic in the streets', 'Noisy neighbours', 'Expensive buses'], correct: 'Too much plastic in the streets', type: 'detail' },
        { q: 'What two solutions does Marina suggest?', opts: ['More recycling bins and school workshops', 'Building a mall and a car park', 'Closing all parks'], correct: 'More recycling bins and school workshops', type: 'detail' },
      ],
      responsePrompt: '¿Estás de acuerdo con Marina? ¿Qué harías en tu barrio?',
    },
    {
      id: '34-r2',
      title: 'Blog: desconexión digital',
      visual: 'A phone turned face-down beside a book.',
      text: 'El fin de semana hice una desconexión digital de 24 horas: apagué las notificaciones y dejé el teléfono en la cocina. Al principio sentí ansiedad: no podía compartir fotos ni ver comentarios ni seguir la tendencia del momento. Luego leí, paseé y hablé con mi familia sin pantallas. Las redes sociales tienen ventajas — nos conectan con amigos — pero el algoritmo nos empuja a compararnos y eso daña la autoestima. Ahora pongo un límite de pantalla por la noche y bloqueo algunas cuentas. No es fácil, pero mi sueño mejoró y estudio con más calma. Recomiendo probarlo un sábado, no en plena semana de exámenes.',
      qs: [
        { q: 'What is the main idea?', opts: ['A personal experiment with a digital detox', 'Instructions to create an account', 'A news report about a new app'], correct: 'A personal experiment with a digital detox', type: 'main' },
        { q: 'What improved after the experiment?', opts: ['Their sleep', 'Their number of followers', 'Their exam timetable'], correct: 'Their sleep', type: 'detail' },
        { q: 'According to the writer, what does the algorithm push people to do?', opts: ['Compare themselves with others', 'Study more grammar', 'Travel more'], correct: 'Compare themselves with others', type: 'detail' },
      ],
      responsePrompt: '¿Podrías estar 24 horas sin redes? ¿Por qué sí o por qué no?',
    },
    {
      id: '34-r3',
      title: 'Diario de un intercambio',
      visual: 'A stamped postcard and a small flag.',
      text: 'Llevo tres semanas en Valencia con una familia anfitriona. Al principio las costumbres me parecían extrañas: se cena muy tarde, el instituto es enorme y hay mucha diversidad de idiomas. Ahora me adapto poco a poco. Ayer visité un mercado y hablé con una vendedora sobre el patrimonio de la ciudad; cometí errores, pero ella tuvo paciencia. La hospitalidad de mi familia anfitriona me ayuda cuando extraño mi casa. Este viaje está cambiando mi identidad: ya no veo “el extranjero” como algo lejano. Quiero explorar más pueblos y, cuando vuelva, seguir el intercambio con cartas. Es un desafío, pero también una oportunidad.',
      qs: [
        { q: 'How does the writer’s attitude change?', opts: ['From finding customs strange to starting to adapt', 'From loving the food to leaving early', 'From speaking perfectly to refusing to talk'], correct: 'From finding customs strange to starting to adapt', type: 'main' },
        { q: 'What did they do yesterday?', opts: ['Visited a market and talked about the city’s heritage', 'Took a final exam', 'Moved to another country'], correct: 'Visited a market and talked about the city’s heritage', type: 'detail' },
        { q: 'What convention of text is this?', opts: ['A personal diary / journal entry', 'An official law', 'A science textbook'], correct: 'A personal diary / journal entry', type: 'purpose' },
      ],
      responsePrompt: '¿Te gustaría hacer un intercambio? Explica una ventaja y un desafío.',
    },
    {
      id: '34-r4',
      title: 'Infografía: salud en el instituto',
      visual: 'Three icons: a moon, a running shoe, a speech bubble.',
      text: '¿Cómo cuidar el bienestar en época de exámenes? 1) Dormir entre siete y ocho horas. El estrés baja si hay descanso de verdad, no solo “cinco minutos más” con el teléfono. 2) Hacer ejercicio tres veces por semana, aunque sea caminar o estirar en el pasillo. 3) Pedir apoyo: hablar con un amigo, un profesor o la familia reduce la ansiedad. La prevención es mejor que esperar a sentirse mal. Pequeños hábitos — hidratarse, una alimentación más equilibrada, un horario de sueño — construyen autoestima. Este cartel es para estudiantes, no para vender un producto. Empieza con un cambio esta semana.',
      qs: [
        { q: 'Who is the likely audience?', opts: ['Students during exam season', 'Restaurant chefs', 'Airline pilots only'], correct: 'Students during exam season', type: 'purpose' },
        { q: 'How much sleep is recommended?', opts: ['Seven to eight hours', 'Three hours', 'Twelve hours every afternoon'], correct: 'Seven to eight hours', type: 'detail' },
        { q: 'What is said about prevention?', opts: ['It is better than waiting until you feel bad', 'It is a waste of time', 'It only works for adults'], correct: 'It is better than waiting until you feel bad', type: 'detail' },
      ],
      responsePrompt: '¿Cuál de los tres consejos es más importante para ti? ¿Por qué?',
    },
    {
      id: '34-r5',
      title: 'Artículo breve: voluntariado',
      visual: 'Volunteers packing food boxes.',
      text: 'Cada sábado, un grupo de estudiantes colabora con una ONG local cerca del mercado. No resuelven la pobreza en un día, pero su solidaridad tiene impacto: clasifican alimentos, practican idiomas con personas refugiadas y organizan una campaña contra la discriminación. “La injusticia nos parece lejana hasta que conoces una historia real”, dice Omar, de dieciséis años. El acceso a la educación, insiste, debería ser un derecho, no un privilegio. Algunos vecinos dudan; otros traen ropa y libros. El artículo no pide un milagro, sino cooperación: una hora a la semana ya cambia la conversación en el instituto. La paz empieza, según Omar, cuando dejas de ver al otro como un problema.',
      qs: [
        { q: 'What is the author’s attitude toward the students’ work?', opts: ['Respectful: small actions still matter', 'Mocking: volunteering is useless', 'Neutral listing of sports scores'], correct: 'Respectful: small actions still matter', type: 'main' },
        { q: 'What activities are mentioned?', opts: ['Sorting food, language practice, and an anti-discrimination campaign', 'Only playing video games', 'Building a highway'], correct: 'Sorting food, language practice, and an anti-discrimination campaign', type: 'detail' },
        { q: 'What does Omar say about injustice?', opts: ['It feels distant until you hear a real story', 'It does not exist', 'It is only about climate'], correct: 'It feels distant until you hear a real story', type: 'detail' },
      ],
      responsePrompt: '¿Qué causa social te importa y qué podrías hacer en tu comunidad?',
    },
    {
      id: '34-r6',
      title: 'Correo: prácticas de verano',
      visual: 'An email header addressed to a student.',
      text: 'Hola Laura: Gracias por enviar tu currículum tan rápido. Podemos ofrecerte prácticas en la biblioteca municipal en julio. El horario es de 10:00 a 14:00, de lunes a jueves; los viernes hay formación opcional. Buscamos a alguien responsable, con ganas de aprender y con habilidad para organizar eventos pequeños, por ejemplo un club de lectura. En la entrevista del viernes habla de tus metas a largo plazo y de un desafío que hayas superado. Trae una idea para un taller. Si tienes dudas sobre el transporte, escríbeme. Un saludo, Sr. Vega, coordinador de prácticas.',
      qs: [
        { q: 'What is the purpose of this email?', opts: ['To offer an internship and explain next steps', 'To cancel a holiday', 'To sell books'], correct: 'To offer an internship and explain next steps', type: 'purpose' },
        { q: 'What should Laura talk about in the interview?', opts: ['Her goals and a challenge she has overcome', 'Her favourite TV series only', 'The weather in January'], correct: 'Her goals and a challenge she has overcome', type: 'detail' },
        { q: 'Which qualities are they looking for?', opts: ['Responsibility, willingness to learn, and organising skills', 'Only a driving licence', 'Professional football experience'], correct: 'Responsibility, willingness to learn, and organising skills', type: 'detail' },
      ],
      responsePrompt: 'Si fueras Laura, ¿aceptarías? Escribe un correo corto de respuesta.',
    },
  ],
};

export const speakingByLevel = {
  '12': {
    echo: [
      'Me llamo {name} y tengo catorce años.',
      'Mi familia vive en Noruega.',
      'Los fines de semana juego al fútbol con mis amigos.',
      'Mi comida favorita es la pizza con queso.',
      'Me gusta leer libros y ver películas.',
      'Por la mañana me despierto a las siete y desayuno.',
      'En mi casa hay una cocina y un dormitorio grande.',
      'Mi asignatura favorita es el español.',
      'Los sábados voy al parque con mi perro.',
      'Por la noche ceno con mi familia y luego descanso.',
    ],
    open: [
      { id: '12-so-1', prompt: 'Preséntate: ¿cómo te llamas, cuántos años tienes y dónde vives?' },
      { id: '12-so-2', prompt: 'Describe a una persona de tu familia en tres frases.' },
      { id: '12-so-3', prompt: '¿Qué haces por la mañana antes del colegio?' },
      { id: '12-so-4', prompt: 'Habla de tu comida favorita y cuándo la comes.' },
      { id: '12-so-5', prompt: 'Describe tu habitación: ¿qué hay?' },
      { id: '12-so-6', prompt: '¿Qué te gusta hacer los fines de semana?' },
      { id: '12-so-7', prompt: '¿Cuál es tu clase favorita y por qué?' },
      { id: '12-so-8', prompt: 'Invita a un amigo a hacer algo el sábado.' },
    ],
  },
  '34': {
    echo: [
      'Creo que es importante proteger el medio ambiente para las futuras generaciones.',
      'En mi opinión, las redes sociales tienen ventajas y desventajas.',
      'Durante mi intercambio, aprendí mucho sobre otra cultura.',
      'Es fundamental que los jóvenes se involucren en causas sociales.',
      'Todavía no he decidido qué carrera quiero estudiar en la universidad.',
      'Para reducir el estrés, intento dormir bien y hacer ejercicio.',
      'El turismo sostenible puede proteger el patrimonio de una ciudad.',
      'Ojalá que más gente recicle y reduzca el plástico.',
      'La solidaridad es esencial cuando hablamos de migración y pobreza.',
      'El año pasado superé un desafío y gané mucha confianza.',
    ],
    open: [
      { id: '34-so-1', prompt: 'Da tu opinión: ¿las redes sociales ayudan o perjudican a los jóvenes?' },
      { id: '34-so-2', prompt: 'Describe un problema ambiental en tu comunidad y una posible solución.' },
      { id: '34-so-3', prompt: 'Cuenta un viaje o una experiencia cultural (usa pasado).' },
      { id: '34-so-4', prompt: '¿Qué hábitos te ayudan a cuidar tu bienestar? Explica.' },
      { id: '34-so-5', prompt: '¿Deberían los institutos enseñar más sobre noticias falsas? ¿Por qué?' },
      { id: '34-so-6', prompt: 'Habla de una profesión que te interesa y de un desafío de esa carrera.' },
      { id: '34-so-7', prompt: '¿Qué significa para ti la solidaridad? Da un ejemplo concreto.' },
      { id: '34-so-8', prompt: 'Compara dos opciones de futuro (estudio, viaje, trabajo) usando comparativos.' },
    ],
  },
};

export const writingPromptsByLevel = {
  '12': [
    {
      id: '12-w1',
      prompt: 'Escribe sobre tu familia. Usa el verbo "tener" y adjetivos posesivos (mi, tu, su).',
      goal: 60,
      checklist: [
        'Used tener (tengo / tiene / tenemos) at least twice',
        'Used possessive adjectives (mi, mis, tu, su)',
        'Checked gender: el/la, un/una, adjective endings',
        'Included at least one connector (y, pero, también)',
        'Used accents where needed (á, é, í, ó, ú, ñ)',
      ],
      model: 'Me llamo Alex y tengo una familia pequeña. Tengo un hermano y una hermana. Mi madre es profesora y mi padre trabaja en un hospital. Mis abuelos viven cerca, pero no veo a mis tíos todos los días. También tenemos una mascota: un perro muy simpático.',
    },
    {
      id: '12-w2',
      prompt: 'Describe tu rutina diaria. Usa al menos cinco verbos en presente.',
      goal: 60,
      checklist: [
        'At least five present-tense verbs (me levanto, desayuno, voy…)',
        'Used reflexive verbs where needed (despertarse, vestirse)',
        'Included times or order words (luego, después, a las siete)',
        'Sentences are complete (subject + verb)',
        'Accents on words like también, después, rápido if used',
      ],
      model: 'Por la mañana me despierto a las siete y me ducho. Desayuno pan y leche. Luego voy al colegio en autobús. Por la tarde estudio y hago la tarea. A las nueve ceno con mi familia y me acuesto.',
    },
    {
      id: '12-w3',
      prompt: 'Escribe un párrafo sobre tu comida favorita y por qué te gusta.',
      goal: 60,
      checklist: [
        'Named the food and when you eat it',
        'Gave at least one reason (porque…)',
        'Used food vocabulary from the topic',
        'Agreement: la pizza está / el arroz es…',
        'At least two connectors (y, porque, también)',
      ],
      model: 'Mi comida favorita es la pizza con queso. La como los viernes con mi familia. Me gusta porque es caliente y fácil de compartir. También me gusta la ensalada, pero la pizza es mejor para una fiesta. Bebo agua, no zumo.',
    },
    {
      id: '12-w4',
      prompt: 'Describe tu casa: ¿cuántas habitaciones tiene? ¿Qué hay en tu dormitorio?',
      goal: 60,
      checklist: [
        'Said what type of home it is (casa / piso)',
        'Named at least four rooms or objects',
        'Used hay / tiene',
        'Described your bedroom with two details',
        'Checked el/la and un/una',
      ],
      model: 'Vivo en un piso. Hay una cocina, una sala, un baño y dos dormitorios. Mi habitación tiene una cama, un armario y una ventana. Hay una lámpara cerca de la mesa. Me gusta mi casa porque es tranquila.',
    },
    {
      id: '12-w5',
      prompt: 'Escribe sobre tus actividades de tiempo libre. ¿Qué te gusta hacer los fines de semana?',
      goal: 60,
      checklist: [
        'Used me gusta / me gustan correctly',
        'Mentioned at least two activities',
        'Said when (los sábados, por la tarde…)',
        'Included friends or family if relevant',
        'One sentence with pero or porque',
      ],
      model: 'Los fines de semana me gusta jugar al fútbol y leer. El sábado voy al parque con mis amigos. El domingo descanso en casa y veo una película. No me gusta correr cuando hace frío, pero me gusta pasear.',
    },
    {
      id: '12-w6',
      prompt: 'Escribe un mensaje a un amigo para invitarle a hacer algo.',
      goal: 60,
      checklist: [
        'Greeting and a clear invitation',
        'Day, time, and place',
        'A plan if something goes wrong (si llueve…)',
        'A question asking them to reply',
        'Friendly closing',
      ],
      model: 'Hola, ¿qué tal? ¿Quieres ir al cine el sábado a las cinco? Después podemos ir al parque. Si llueve, vamos a mi casa y jugamos. Respóndeme, por favor. Hasta pronto.',
    },
    {
      id: '12-w7',
      prompt: 'Describe tu colegio: asignaturas, profesores y un lugar que te gusta (biblioteca, patio…).',
      goal: 60,
      checklist: [
        'Named the school or type of school',
        'Mentioned at least two subjects',
        'Described one place in the school',
        'Gave an opinion (me gusta / no me gusta)',
        'Used ser or estar correctly at least once',
      ],
      model: 'Mi colegio es grande. Tengo español, matemáticas y arte. Mi profesora de español es simpática. Me gusta la biblioteca porque está tranquila y hay muchos libros. El recreo es en el patio, pero a veces estudio en un pupitre cerca de la pizarra.',
    },
    {
      id: '12-w8',
      prompt: 'Escribe cinco frases sobre un día especial (cumpleaños, fiesta o visita).',
      goal: 60,
      checklist: [
        'Said what the day is',
        'Mentioned people and a place',
        'Used present tense consistently',
        'Included food or an activity',
        'One feeling word (contento/a, cansado/a, feliz)',
      ],
      model: 'Hoy es el cumpleaños de mi hermana. Toda la familia está en casa. Hay un postre de chocolate en la mesa. Cantamos y bailamos en la sala. Estoy muy feliz porque mis primos también están aquí.',
    },
  ],
  '34': [
    {
      id: '34-w1',
      prompt: 'Escribe un texto de opinión sobre el impacto de las redes sociales en los jóvenes. Usa el subjuntivo al menos dos veces.',
      goal: 120,
      checklist: [
        'Clear opinion in the introduction',
        'At least two subjunctive forms (espero que, es importante que…)',
        'One advantage and one disadvantage',
        'Connectors: aunque, sin embargo, por eso',
        'Short conclusion with a recommendation',
      ],
      model: 'En mi opinión, las redes sociales conectan a los jóvenes, pero también pueden causar ansiedad. Es importante que pongamos límites a la pantalla. Aunque compartir fotos es divertido, no creo que sea sano compararse todo el día. Espero que las escuelas enseñen privacidad y respeto. Por eso, recomiendo una desconexión digital los fines de semana.',
    },
    {
      id: '34-w2',
      prompt: 'Narra un viaje o una experiencia pasada. Usa pretérito e imperfecto.',
      goal: 120,
      checklist: [
        'At least three preterite verbs for completed actions',
        'At least two imperfect verbs for description or habit',
        'Time markers (el año pasado, mientras, de repente)',
        'A feeling or reflection at the end',
        'Varied vocabulary (not only fue / era)',
      ],
      model: 'El verano pasado viajé a Valencia con mi instituto. El cielo estaba azul y la gente era muy hospitalaria. Mientras visitábamos el mercado, de repente empezó a llover. Comimos paella y hablé con una guía sobre el patrimonio de la ciudad. Al final, superé mi miedo a hablar español y volví con más confianza.',
    },
    {
      id: '34-w3',
      prompt: 'Escribe una carta a un periódico sobre un problema medioambiental en tu comunidad y propone soluciones.',
      goal: 120,
      checklist: [
        'Letter format (greeting, closing)',
        'Problem described with details',
        'At least two concrete solutions',
        'Formal or semi-formal tone',
        'Subjunctive or recommendation language (es necesario que, propongo que)',
      ],
      model: 'Estimado director: Escribo porque en mi barrio hay demasiado plástico y las emisiones de los coches son altas. El parque sufre la sequía y hay poca biodiversidad. Es necesario que el ayuntamiento ponga más contenedores y que reduzcamos el desperdicio en el colegio. Propongo talleres de reciclaje y más energía renovable en los edificios públicos. Atentamente, un/a estudiante de MYP4.',
    },
    {
      id: '34-w4',
      prompt: 'Compara dos posibles carreras o caminos después del instituto. Usa comparativos y superlativos.',
      goal: 120,
      checklist: [
        'Two options clearly named',
        'más/menos...que or tan...como at least twice',
        'One irregular comparative (mejor, peor, mayor, menor) if possible',
        'Personal reason for a preference',
        'A concluding sentence about the future',
      ],
      model: 'Me interesan la medicina y el diseño. La medicina es más exigente que el diseño, pero también puede ser más útil para la comunidad. El diseño es menos estresante para mí y tan creativo como el arte. Para mi familia, la universidad de medicina es la mejor opción; para mí, no es la peor idea el diseño si hago prácticas. Todavía no he tomado una decisión.',
    },
    {
      id: '34-w5',
      prompt: 'Escribe sobre un problema global que te preocupa (pobreza, migración, desigualdad) y explica por qué hay que actuar.',
      goal: 120,
      checklist: [
        'Named the issue and who is affected',
        'Explained why it matters (porque / ya que)',
        'Used at least four topic words (derechos, solidaridad, ONG…)',
        'Proposed one action young people can take',
        'Cohesive paragraphing (intro, development, close)',
      ],
      model: 'La desigualdad en el acceso a la educación me preocupa porque limita el futuro de muchas personas. La pobreza y la migración a menudo van juntas: hay quien busca paz y trabajo. Las ONG no resuelven todo, pero la solidaridad local ayuda. Es fundamental que los jóvenes se informen y hagan voluntariado. La justicia social no es automática; hay que defender los derechos humanos cada día.',
    },
    {
      id: '34-w6',
      prompt: 'Da consejos para el bienestar en época de exámenes. Incluye al menos dos frases con subjuntivo o recomendación.',
      goal: 120,
      checklist: [
        'Audience is clear (compañeros / jóvenes)',
        'At least three concrete habits (sleep, exercise, support)',
        'Two recommendation structures (te aconsejo que, es mejor que…)',
        'Mention of stress or anxiety with appropriate vocab',
        'Encouraging closing',
      ],
      model: 'En época de exámenes el estrés es normal, pero no debe controlar tu semana. Te aconsejo que duermas siete horas y que hagas ejercicio, aunque sea caminar. Es mejor que hables con alguien de confianza si hay ansiedad. Un hábito pequeño, como dejar el teléfono fuera del dormitorio, mejora el sueño. Si cuidas tu salud mental ahora, llegas más equilibrado/a al examen.',
    },
    {
      id: '34-w7',
      prompt: 'Escribe un correo formal para solicitar prácticas o un intercambio. Incluye metas y un desafío superado.',
      goal: 120,
      checklist: [
        'Email greeting and polite closing',
        'Why you are writing in the first paragraph',
        'Mention of skills or a past experience (preterite)',
        'A challenge you overcame',
        'A clear question or request at the end',
      ],
      model: 'Estimado Sr. Vega: Le escribo para solicitar las prácticas de julio en la biblioteca. Soy estudiante de MYP4, responsable y con ganas de aprender. El año pasado organicé un evento escolar y superé el miedo a hablar en público. Mi meta es mejorar el español y ganar experiencia. ¿Podría confirmarme la hora de la entrevista? Un saludo cordial.',
    },
    {
      id: '34-w8',
      prompt: '¿El turismo ayuda o daña una ciudad? Escribe un texto argumentativo corto con ejemplos.',
      goal: 120,
      checklist: [
        'Thesis stated clearly',
        'One argument in favour and one against',
        'Example related to heritage, economy, or waste',
        'Connectors of contrast (sin embargo, aunque)',
        'Balanced conclusion (sustainable tourism / conditions)',
      ],
      model: 'El turismo puede ayudar a la economía local y al intercambio cultural. Sin embargo, si no es sostenible, daña el patrimonio y genera demasiada basura. En mi ciudad, los visitantes son bienvenidos, aunque las calles históricas se llenan en verano. Creo que es el peor modelo cuando solo hay fotos y no respeto. Un turismo mejor es posible si hay límites y educación.',
    },
  ],
};

export function interpolateName(text, name) {
  const n = (name && name.trim()) || 'Alex';
  return text.replaceAll('{name}', n);
}

export function allVocab(level) {
  const sets = vocabSetsByLevel[level] || {};
  return Object.values(sets).flat();
}

export function vocabTopicOf(level, id) {
  const sets = vocabSetsByLevel[level] || {};
  for (const [topic, items] of Object.entries(sets)) {
    if (items.some((item) => item.id === id)) return topic;
  }
  return '';
}

export function findVocab(level, id) {
  return allVocab(level).find((item) => item.id === id) || null;
}

export function grammarItems(level, topic) {
  return grammarSetsByLevel[level][topic]?.qs || [];
}

export function allGrammarItems(level) {
  const sets = grammarSetsByLevel[level] || {};
  const out = [];
  for (const [topic, data] of Object.entries(sets)) {
    for (const q of data.qs) out.push({ ...q, topic });
  }
  return out;
}

export function topicNames(level, which) {
  if (which === 'vocab') return Object.keys(vocabSetsByLevel[level] || {});
  if (which === 'grammar') return Object.keys(grammarSetsByLevel[level] || {});
  return [];
}
